package com.self.more.Regex.RegexJudgeBasis;

public class RegexDemo {
    public static void main(String[] args) {
        System.out.println("a".matches("[abc]"));
        System.out.println("d".matches("[abc]"));
        System.out.println("ab".matches("[abc]"));
        System.out.println("=============================");
        System.out.println("d".matches("[^abc]"));
        System.out.println("a".matches("[^abc]]"));
        System.out.println("de".matches("[^abc]"));
        System.out.println("=============================");
        System.out.println("Z".matches("[a-zA-Z]"));
        System.out.println("2".matches("[a-zA-Z]"));
        System.out.println("=============================");
        System.out.println("p".matches("[a-d]|[m-p]"));
        System.out.println("e".matches("[a-z&&def]"));
        System.out.println("b".matches("[a-z&&[^bc]]"));
        System.out.println("m".matches("[a-z&&[^m-p]]"));
        System.out.println("=============================");
        System.out.println(" ".matches("."));
        System.out.println("6".matches("."));
        System.out.println("=============================");
        System.out.println("6".matches("\\d"));
        System.out.println("z".matches("\\d"));
        System.out.println("6".matches("\\D"));
        System.out.println("z".matches("\\D"));
        System.out.println("=============================");
        System.out.println(" ".matches("\\s"));
        System.out.println("2".matches("\\s"));
        System.out.println(" ".matches("\\S"));
        System.out.println("2".matches("\\S"));
        System.out.println("=============================");
        System.out.println("_".matches("\\w"));
        System.out.println("A".matches("\\w"));
        System.out.println("陈".matches("\\w"));
        System.out.println("陈".matches("\\W"));
        System.out.println("A".matches("\\W"));
        System.out.println("=============================");
        System.out.println("1".matches("\\d?"));
        System.out.println("".matches("\\d?"));
        System.out.println("d".matches("\\d?"));
        System.out.println("=============================");
        System.out.println("151351".matches("\\d*"));
        System.out.println("".matches("\\d*"));
        System.out.println("1564A446".matches("\\d*"));
        System.out.println("=============================");
        System.out.println("1531".matches("\\d+"));
        System.out.println("".matches("\\d+"));
        System.out.println("13135Adawd513".matches("\\d+"));
        System.out.println("=============================");
        System.out.println("123456".matches("\\d{6}"));
        System.out.println("123456".matches("\\d{5}"));
        System.out.println("12345A".matches("\\d{6}"));
        System.out.println("=============================");
        System.out.println("12".matches("\\d{2,}"));
        System.out.println("1".matches("\\d{2,}"));
        System.out.println("123".matches("\\d{2,}"));
        System.out.println("=============================");
        System.out.println("123".matches("\\d{2,6}"));
        System.out.println("1234567".matches("\\d{2,6}"));
        System.out.println("=============================");
        System.out.println("Abc".matches("(?i)abc"));
        System.out.println("ABC".matches("(?i)abc"));
        System.out.println("aBc".matches("a((?i)b)c"));
        System.out.println("ABc".matches("a((?i)b)c"));
        System.out.println("=============================");
        System.out.println("123".matches("\\d{3}|[a-z]{3}"));
        System.out.println("abc".matches("\\d{3}|[a-z]{3}"));
        System.out.println("=============================");
        System.out.println("中文汉字汉字666666".matches("中文(汉字)+(666)+"));
        System.out.println("中文汉字汉字6666666".matches("中文(汉字)+(666)+"));
    }
}
