
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile:  dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ex?useServerPrepStmts=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: Aa2447439574
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 50MB
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto

#阿里云oss服务配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
    bucketName: learn-upload


#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-runtime-dialect: true

---
spring:
  config:
    activate:
      on-profile:  test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ex?useServerPrepStmts=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Aa2447439574
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile:  prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ex?useServerPrepStmts=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Aa2447439574
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8082



