spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile:  dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ex?useServerPrepStmts=true
    username: root
    password: Aa2447439574
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile:  test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ex?useServerPrepStmts=true
    username: root
    password: Aa2447439574
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile:  prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ex?useServerPrepStmts=true
    username: root
    password: Aa2447439574
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8082




