<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.learnSpringMVC</groupId>
  <artifactId>PomRootProject</artifactId>
  <packaging>pom</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>PomRootProject Maven Webapp</name>
  <url>http://maven.apache.org</url>

  <properties>
    <spring.version>5.2.10.RELEASE</spring.version>
    <javax.servlet-api.version>4.0.1</javax.servlet-api.version>
    <mybatis.version>3.5.6</mybatis.version>
    <mysql-connector-java.version>8.0.33</mysql-connector-java.version>
    <mybatis-spring.version>2.0.6</mybatis-spring.version>
    <druid.version>1.2.27</druid.version>
    <aspectjweaver.version>1.9.8</aspectjweaver.version>
    <jackson.version>2.9.0</jackson.version>
  </properties>



  <dependencies>

    <!-- https://mvnrepository.com/artifact/org.springframework/spring-webmvc -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
      <version>${spring.version}</version>
    </dependency>

    <!-- 使用Java EE servlet API 而不是 Jakarta EE -->
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>${javax.servlet-api.version}</version>
      <scope>provided</scope>
    </dependency>


    <!-- https://mvnrepository.com/artifact/org.springframework/spring-context -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>${spring.version}</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.mybatis/mybatis -->
    <dependency>
      <groupId>org.mybatis</groupId>
      <artifactId>mybatis</artifactId>
      <version>${mybatis.version}</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>${mysql-connector-java.version}</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.springframework/spring-jdbc -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-jdbc</artifactId>
      <version>${spring.version}</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.mybatis/mybatis-spring -->
    <dependency>
      <groupId>org.mybatis</groupId>
      <artifactId>mybatis-spring</artifactId>
      <version>${mybatis-spring.version}</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/com.alibaba/druid -->
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>druid</artifactId>
      <version>${druid.version}</version>
    </dependency>



    <!-- https://mvnrepository.com/artifact/org.springframework/spring-test -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-test</artifactId>
      <version>${spring.version}</version>
      <scope>test</scope>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.aspectj/aspectjweaver -->
    <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjweaver</artifactId>
      <version>${aspectjweaver.version}</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>${jackson.version}</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson.version}</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotations -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>${jackson.version}</version>
    </dependency>
  </dependencies>


  <build>
    <finalName>PomRootProject</finalName>
    <resources>
      <resource>
        <directory>${project.basedir}/src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.2.0</version>
        <configuration>
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>
<!--      <plugin>-->
<!--        <artifactId>maven-surefire-plugin</artifactId>-->
<!--        <version>2.12.4</version>-->
<!--        <configuration>-->
<!--          <skipTests>false</skipTests>-->
<!--          <excludes>-->
<!--            <exclude>**/BrandTest.java</exclude>-->
<!--          </excludes>-->
<!--          <argLine>-Dfile.encoding=utf-8</argLine>-->
<!--        </configuration>-->
<!--      </plugin>-->
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>dev</id>
      <properties>
        <jdbc.url>jdbc:mysql://127.0.0.1:3306/ex?useServerPrepStmts=true</jdbc.url>
      </properties>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>
    <profile>
      <id>test</id>
      <properties>
        <jdbc.url>jdbc:mysql://127.0.0.1:3306/ex?useServerPrepStmts=true</jdbc.url>
      </properties>
    </profile>
    <profile>
      <id>prod</id>
      <properties>
        <jdbc.url>jdbc:mysql://127.0.0.1:3306/ex?useServerPrepStmts=true</jdbc.url>
      </properties>
    </profile>
  </profiles>


  

  <modules>
    <module>../Maven-day01-splitMapper</module>
    <module>../Maven-day01-splitPojo</module>
    <module>../SpringMVC-day01-quickStart</module>
  </modules>
</project>
